"""agrega categoria_error a sincronizaciones_meta

Revision ID: 0b1d48632517
Revises: 4e62bf8cb2ef
Create Date: 2026-08-15 04:10:13.566590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1d48632517'
down_revision = '4e62bf8cb2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincronizaciones_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_error', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincronizaciones_meta', schema=None) as batch_op:
        batch_op.drop_column('categoria_error')

    # ### end Alembic commands ###
