"""agrega categoria y version a presets, favoritos y snapshot de preset en derivados

Revision ID: 137c67bd1eca
Revises: e937a16579b2
Create Date: 2026-08-12 16:21:02.432345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137c67bd1eca'
down_revision = 'e937a16579b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='fk_preset_favoritos_empresa_id_empresas'),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], name='fk_preset_favoritos_preset_id_presets'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'preset_id', name='uq_preset_favorito_empresa_preset')
    )
    with op.batch_alter_table('preset_favoritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preset_favoritos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preset_favoritos_preset_id'), ['preset_id'], unique=False)

    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preset_nombre', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('preset_version', sa.Integer(), nullable=True))

    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_presets_categoria'), ['categoria'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presets_categoria'))
        batch_op.drop_column('version')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.drop_column('preset_version')
        batch_op.drop_column('preset_nombre')

    with op.batch_alter_table('preset_favoritos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preset_favoritos_preset_id'))
        batch_op.drop_index(batch_op.f('ix_preset_favoritos_empresa_id'))
        batch_op.drop_constraint('fk_preset_favoritos_preset_id_presets', type_='foreignkey')
        batch_op.drop_constraint('fk_preset_favoritos_empresa_id_empresas', type_='foreignkey')

    op.drop_table('preset_favoritos')
    # ### end Alembic commands ###
