"""Agrega conversaciones y mensajes del Estratega IA (Paso 10)

Revision ID: 19287f0e235f
Revises: fdff157b5aa8
Create Date: 2026-08-14 12:38:00.844557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19287f0e235f'
down_revision = 'fdff157b5aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_estrategicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversaciones_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversaciones_ia_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('mensajes_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('contexto_utilizado', sa.JSON(), nullable=True),
    sa.Column('acciones_propuestas', sa.JSON(), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('costo_estimado_usd', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_ia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_ia_conversacion_id'), ['conversacion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_ia_conversacion_id'))

    op.drop_table('mensajes_ia')
    with op.batch_alter_table('conversaciones_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversaciones_ia_empresa_id'))

    op.drop_table('conversaciones_ia')
    # ### end Alembic commands ###
