"""agrega fuentes_datos (Paso 2 Centro de Datos)

Revision ID: 4119f610842e
Revises: 0b1d48632517
Create Date: 2026-08-15 10:06:52.331712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4119f610842e'
down_revision = '0b1d48632517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuentes_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.Column('ultimo_error', sa.String(length=500), nullable=True),
    sa.Column('ultima_sincronizacion_en', sa.DateTime(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', name='uq_fuente_datos_empresa_tipo')
    )
    with op.batch_alter_table('fuentes_datos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuentes_datos_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuentes_datos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuentes_datos_empresa_id'))

    op.drop_table('fuentes_datos')
    # ### end Alembic commands ###
