"""Agrega favorito a informes de pauta (Paso 16)

Revision ID: 4e62bf8cb2ef
Revises: f737311b717d
Create Date: 2026-08-14 20:00:20.018918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e62bf8cb2ef'
down_revision = 'f737311b717d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default agregado a mano: sin esto, agregar una columna
    # NOT NULL a una tabla con filas existentes falla en Postgres (no
    # hay valor para las filas ya creadas en el Paso 15). Se quita
    # despues de poblar la columna para que el modelo (default=False a
    # nivel de Python) siga siendo la unica fuente de verdad hacia
    # adelante.
    with op.batch_alter_table('informes_pauta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorito', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('informes_pauta', schema=None) as batch_op:
        batch_op.alter_column('favorito', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informes_pauta', schema=None) as batch_op:
        batch_op.drop_column('favorito')

    # ### end Alembic commands ###
