"""agrega presupuesto de pauta y ultimo_uso_en de conexion (Paso 2)

Revision ID: 559ebdd9c298
Revises: f52e0e6eda0f
Create Date: 2026-08-12 21:24:21.151359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559ebdd9c298'
down_revision = 'f52e0e6eda0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos_pauta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('periodo_tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('objetivo', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_publicitarias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos_pauta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_pauta_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_pauta_entidad_id'), ['entidad_id'], unique=False)

    with op.batch_alter_table('meta_conexiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_uso_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_conexiones', schema=None) as batch_op:
        batch_op.drop_column('ultimo_uso_en')

    with op.batch_alter_table('presupuestos_pauta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_pauta_entidad_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_pauta_empresa_id'))

    op.drop_table('presupuestos_pauta')
    # ### end Alembic commands ###
