"""agrega proyectos de pauta y sus etapas (paso 7)

Revision ID: 762d36bff20f
Revises: 559ebdd9c298
Create Date: 2026-08-13 17:16:47.654541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762d36bff20f'
down_revision = '559ebdd9c298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_pauta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_publicitaria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('objetivo', sa.String(length=120), nullable=False),
    sa.Column('kpi_principal', sa.String(length=60), nullable=False),
    sa.Column('presupuesto_total', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('resultado_objetivo', sa.String(length=200), nullable=True),
    sa.Column('restricciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_publicitaria_id'], ['entidades_publicitarias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos_pauta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_pauta_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('etapas_proyecto_pauta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('objetivo', sa.String(length=120), nullable=True),
    sa.Column('presupuesto', sa.Float(), nullable=False),
    sa.Column('kpi_esperado', sa.String(length=60), nullable=True),
    sa.Column('audiencia_descripcion', sa.String(length=200), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_pauta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas_proyecto_pauta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_proyecto_pauta_proyecto_id'), ['proyecto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapas_proyecto_pauta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_proyecto_pauta_proyecto_id'))

    op.drop_table('etapas_proyecto_pauta')
    with op.batch_alter_table('proyectos_pauta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_pauta_empresa_id'))

    op.drop_table('proyectos_pauta')
    # ### end Alembic commands ###
