"""agrega proyectos fotograficos y fotografias

Revision ID: 76dfc396f01f
Revises: e19759e5bd0f
Create Date: 2026-08-12 01:40:37.859310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dfc396f01f'
down_revision = 'e19759e5bd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_fotograficos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos_fotograficos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_fotograficos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('fotografias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_storage', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('subido_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('ancho_px', sa.Integer(), nullable=True),
    sa.Column('alto_px', sa.Integer(), nullable=True),
    sa.Column('orientacion', sa.Integer(), nullable=True),
    sa.Column('fecha_captura', sa.DateTime(), nullable=True),
    sa.Column('camara', sa.String(length=255), nullable=True),
    sa.Column('lente', sa.String(length=255), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('apertura', sa.String(length=20), nullable=True),
    sa.Column('velocidad_obturacion', sa.String(length=20), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_fotograficos.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotografias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotografias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotografias_proyecto_id'), ['proyecto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotografias_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_fotografias_empresa_id'))

    op.drop_table('fotografias')
    with op.batch_alter_table('proyectos_fotograficos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_fotograficos_empresa_id'))

    op.drop_table('proyectos_fotograficos')
    # ### end Alembic commands ###
