"""agrega fotografias derivadas

Revision ID: 80b0228e4d32
Revises: 76dfc396f01f
Create Date: 2026-08-12 02:18:36.160113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b0228e4d32'
down_revision = '76dfc396f01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotografias_derivadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fotografia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error_mensaje', sa.String(length=500), nullable=True),
    sa.Column('ruta_storage', sa.String(length=500), nullable=True),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('categoria_detectada', sa.String(length=30), nullable=True),
    sa.Column('confianza_categoria', sa.Float(), nullable=True),
    sa.Column('rostros_detectados', sa.Integer(), nullable=True),
    sa.Column('rostros_protegidos', sa.Boolean(), nullable=True),
    sa.Column('correcciones_aplicadas', sa.String(length=255), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fotografia_id'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotografias_derivadas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotografias_derivadas_fotografia_id'), ['fotografia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotografias_derivadas_fotografia_id'))
        batch_op.drop_index(batch_op.f('ix_fotografias_derivadas_empresa_id'))

    op.drop_table('fotografias_derivadas')
    # ### end Alembic commands ###
