"""agrega logo y formato a fotografias derivadas

Revision ID: 95d219eefb24
Revises: 80b0228e4d32
Create Date: 2026-08-12 09:54:33.952590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d219eefb24'
down_revision = '80b0228e4d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aplicacion_logo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('posicion_logo', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('opacidad_logo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ancho_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alto_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('advertencia', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            'fk_fotografias_derivadas_logo_id_logos', 'logos', ['logo_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fotografias_derivadas_logo_id_logos', type_='foreignkey')
        batch_op.drop_column('advertencia')
        batch_op.drop_column('alto_px')
        batch_op.drop_column('ancho_px')
        batch_op.drop_column('opacidad_logo')
        batch_op.drop_column('posicion_logo')
        batch_op.drop_column('aplicacion_logo')
        batch_op.drop_column('logo_id')

    # ### end Alembic commands ###
