"""Agrega acciones controladas sobre Meta (Paso 12)

Revision ID: ba240d3c3b14
Revises: 19287f0e235f
Create Date: 2026-08-14 13:19:35.941664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba240d3c3b14'
down_revision = '19287f0e235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_accion', sa.String(length=30), nullable=False),
    sa.Column('valor_actual', sa.String(length=60), nullable=True),
    sa.Column('valor_propuesto', sa.String(length=60), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.Column('riesgo', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('propuesto_por', sa.String(length=36), nullable=True),
    sa.Column('aprobado_por', sa.String(length=36), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(), nullable=True),
    sa.Column('ejecutado_en', sa.DateTime(), nullable=True),
    sa.Column('resultado_meta', sa.JSON(), nullable=True),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_publicitarias.id'], ),
    sa.ForeignKeyConstraint(['propuesto_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acciones_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acciones_meta_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acciones_meta_entidad_id'), ['entidad_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acciones_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acciones_meta_entidad_id'))
        batch_op.drop_index(batch_op.f('ix_acciones_meta_empresa_id'))

    op.drop_table('acciones_meta')
    # ### end Alembic commands ###
