"""agrega decisiones_clave a proyectos_estrategicos (Paso 3)

Revision ID: ce1137a12f8e
Revises: 4119f610842e
Create Date: 2026-08-15 10:45:16.171531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1137a12f8e'
down_revision = '4119f610842e'
branch_labels = None
depends_on = None


def upgrade():
    # Agregar una columna NOT NULL a una tabla con filas existentes en
    # produccion (Postgres) requiere un server_default temporal -- ver
    # el mismo patron de dos bloques usado para InformePauta.favorito
    # (Paso 16). Se limpia despues porque el default real (lista vacia)
    # ya lo controla el modelo (default=list), no la base de datos.
    with op.batch_alter_table('proyectos_estrategicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decisiones_clave', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    with op.batch_alter_table('proyectos_estrategicos', schema=None) as batch_op:
        batch_op.alter_column('decisiones_clave', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_estrategicos', schema=None) as batch_op:
        batch_op.drop_column('decisiones_clave')

    # ### end Alembic commands ###
