"""agrega metadata de encuadre a fotografias derivadas

Revision ID: da1e4068b594
Revises: 95d219eefb24
Create Date: 2026-08-12 10:36:15.848777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1e4068b594'
down_revision = '95d219eefb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_mode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('focus_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('focus_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crop_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crop_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crop_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crop_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('algoritmo_recorte', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.drop_column('algoritmo_recorte')
        batch_op.drop_column('crop_height')
        batch_op.drop_column('crop_width')
        batch_op.drop_column('crop_y')
        batch_op.drop_column('crop_x')
        batch_op.drop_column('focus_y')
        batch_op.drop_column('focus_x')
        batch_op.drop_column('crop_mode')

    # ### end Alembic commands ###
