"""agrega proyectos_marketing paso 4

Revision ID: e58444c07306
Revises: ce1137a12f8e
Create Date: 2026-08-16 20:22:45.430495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58444c07306'
down_revision = 'ce1137a12f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_marketing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('objetivo_tipo', sa.String(length=40), nullable=True),
    sa.Column('objetivo_detalle', sa.Text(), nullable=True),
    sa.Column('publico', sa.JSON(), nullable=False),
    sa.Column('oferta', sa.JSON(), nullable=False),
    sa.Column('accion_deseada', sa.String(length=40), nullable=True),
    sa.Column('accion_detalle', sa.Text(), nullable=True),
    sa.Column('presupuesto_produccion', sa.Float(), nullable=True),
    sa.Column('presupuesto_pauta', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('sin_fecha_definida', sa.Boolean(), nullable=False),
    sa.Column('identidad_marca_brief', sa.JSON(), nullable=False),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos_marketing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_marketing_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_marketing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_marketing_empresa_id'))

    op.drop_table('proyectos_marketing')
    # ### end Alembic commands ###
