"""agrega presets, sesiones fotograficas y sesion_id a derivados

Revision ID: e937a16579b2
Revises: da1e4068b594
Create Date: 2026-08-12 13:45:13.648012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e937a16579b2'
down_revision = 'da1e4068b594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presets_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presets_slug'), ['slug'], unique=False)

    op.create_table('sesiones_fotograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('aplicacion_logo', sa.String(length=20), nullable=True),
    sa.Column('posicion_logo', sa.String(length=30), nullable=True),
    sa.Column('opacidad_logo', sa.Float(), nullable=True),
    sa.Column('formatos_seleccionados', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('total_fotografias', sa.Integer(), nullable=False),
    sa.Column('completadas', sa.Integer(), nullable=False),
    sa.Column('errores', sa.Integer(), nullable=False),
    sa.Column('analisis_brillo_promedio', sa.Float(), nullable=True),
    sa.Column('analisis_contraste_promedio', sa.Float(), nullable=True),
    sa.Column('analisis_saturacion_promedio', sa.Float(), nullable=True),
    sa.Column('analisis_temperatura_predominante', sa.String(length=20), nullable=True),
    sa.Column('analisis_duracion_segundos', sa.Float(), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['logo_id'], ['logos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_fotograficos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones_fotograficas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_fotograficas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesiones_fotograficas_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('sesion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('fotografia_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error_mensaje', sa.String(length=500), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fotografia_id'], ['fotografias.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_fotograficas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesion_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesion_items_fotografia_id'), ['fotografia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesion_items_sesion_id'), ['sesion_id'], unique=False)

    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sesion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preset_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fotografias_derivadas_sesion_id'), ['sesion_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_fotografias_derivadas_preset_id_presets', 'presets', ['preset_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_fotografias_derivadas_sesion_id_sesiones_fotograficas',
            'sesiones_fotograficas', ['sesion_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###

    # Nota: los 11 presets de sistema NO se siembran aqui. Se probo con
    # op.bulk_insert() pero no persistia de forma confiable bajo el modo
    # "non-transactional DDL" que Alembic usa para SQLite en este
    # proyecto. En su lugar, la siembra es idempotente y ocurre desde
    # la aplicacion (ver app/services/presets.py::sembrar_presets_sistema,
    # llamada en create_app()) -- funciona igual en SQLite y Postgres,
    # y no depende de como Alembic maneje la transaccion.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias_derivadas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fotografias_derivadas_sesion_id_sesiones_fotograficas', type_='foreignkey')
        batch_op.drop_constraint('fk_fotografias_derivadas_preset_id_presets', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fotografias_derivadas_sesion_id'))
        batch_op.drop_column('preset_id')
        batch_op.drop_column('sesion_id')

    with op.batch_alter_table('sesion_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesion_items_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_sesion_items_fotografia_id'))

    op.drop_table('sesion_items')
    with op.batch_alter_table('sesiones_fotograficas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_fotograficas_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_sesiones_fotograficas_empresa_id'))

    op.drop_table('sesiones_fotograficas')
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presets_slug'))
        batch_op.drop_index(batch_op.f('ix_presets_empresa_id'))

    op.drop_table('presets')
    # ### end Alembic commands ###
