"""agrega Datos de Meta: conexiones, entidades, sincronizaciones y motor de metricas

Revision ID: f52e0e6eda0f
Revises: 3e4447045c34
Create Date: 2026-08-12 21:02:38.308685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52e0e6eda0f'
down_revision = '3e4447045c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('nombre_mostrado', sa.String(length=120), nullable=False),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('tipo_valor', sa.String(length=20), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('formula', sa.String(length=255), nullable=True),
    sa.Column('niveles_aplicables', sa.JSON(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_metricas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_metricas_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalogo_metricas_fuente'), ['fuente'], unique=False)

    op.create_table('meta_conexiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('meta_user_id', sa.String(length=64), nullable=False),
    sa.Column('nombre_usuario_meta', sa.String(length=255), nullable=True),
    sa.Column('access_token_cifrado', sa.Text(), nullable=False),
    sa.Column('token_expira_en', sa.DateTime(), nullable=True),
    sa.Column('scopes_concedidos', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ultimo_error', sa.String(length=500), nullable=True),
    sa.Column('ultima_sincronizacion_en', sa.DateTime(), nullable=True),
    sa.Column('conectado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conectado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meta_conexiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_conexiones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('entidades_publicitarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=True),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('entidad_padre_id', sa.Integer(), nullable=True),
    sa.Column('id_externo', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('sincronizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conexion_id'], ['meta_conexiones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidad_padre_id'], ['entidades_publicitarias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'conexion_id', 'id_externo', name='uq_entidad_publicitaria_fuente_conexion_externo')
    )
    with op.batch_alter_table('entidades_publicitarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_publicitarias_conexion_id'), ['conexion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entidades_publicitarias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entidades_publicitarias_entidad_padre_id'), ['entidad_padre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entidades_publicitarias_fuente'), ['fuente'], unique=False)
        batch_op.create_index(batch_op.f('ix_entidades_publicitarias_tipo'), ['tipo'], unique=False)

    op.create_table('sincronizaciones_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio_periodo', sa.Date(), nullable=True),
    sa.Column('fecha_fin_periodo', sa.Date(), nullable=True),
    sa.Column('registros_procesados', sa.Integer(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error_mensaje', sa.String(length=500), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(), nullable=True),
    sa.Column('finalizada_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['meta_conexiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sincronizaciones_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sincronizaciones_meta_conexion_id'), ['conexion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizaciones_meta_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=30), nullable=True),
    sa.Column('metrica_nombre', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('valor_texto', sa.String(length=255), nullable=True),
    sa.Column('tipo_valor', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('sincronizacion_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_publicitarias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sincronizacion_id'], ['sincronizaciones_meta.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.create_index('ix_metricas_empresa_entidad_metrica_fecha', ['empresa_id', 'entidad_id', 'metrica_nombre', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_metricas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metricas_entidad_id'), ['entidad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metricas_entidad_tipo'), ['entidad_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_metricas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_metricas_metrica_nombre'), ['metrica_nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metricas_metrica_nombre'))
        batch_op.drop_index(batch_op.f('ix_metricas_fecha'))
        batch_op.drop_index(batch_op.f('ix_metricas_entidad_tipo'))
        batch_op.drop_index(batch_op.f('ix_metricas_entidad_id'))
        batch_op.drop_index(batch_op.f('ix_metricas_empresa_id'))
        batch_op.drop_index('ix_metricas_empresa_entidad_metrica_fecha')

    op.drop_table('metricas')
    with op.batch_alter_table('sincronizaciones_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sincronizaciones_meta_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_sincronizaciones_meta_conexion_id'))

    op.drop_table('sincronizaciones_meta')
    with op.batch_alter_table('entidades_publicitarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_publicitarias_tipo'))
        batch_op.drop_index(batch_op.f('ix_entidades_publicitarias_fuente'))
        batch_op.drop_index(batch_op.f('ix_entidades_publicitarias_entidad_padre_id'))
        batch_op.drop_index(batch_op.f('ix_entidades_publicitarias_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_entidades_publicitarias_conexion_id'))

    op.drop_table('entidades_publicitarias')
    with op.batch_alter_table('meta_conexiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_conexiones_empresa_id'))

    op.drop_table('meta_conexiones')
    with op.batch_alter_table('catalogo_metricas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_metricas_fuente'))
        batch_op.drop_index(batch_op.f('ix_catalogo_metricas_clave'))

    op.drop_table('catalogo_metricas')
    # ### end Alembic commands ###
