"""Agrega informes de pauta (Paso 15)

Revision ID: f737311b717d
Revises: ba240d3c3b14
Create Date: 2026-08-14 14:50:52.370231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f737311b717d'
down_revision = 'ba240d3c3b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informes_pauta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_publicitaria_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('periodo_clave', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('tipo_comparacion', sa.String(length=30), nullable=False),
    sa.Column('filtros', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.JSON(), nullable=True),
    sa.Column('resumen_generado_por', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_publicitaria_id'], ['entidades_publicitarias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informes_pauta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_informes_pauta_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informes_pauta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_informes_pauta_empresa_id'))

    op.drop_table('informes_pauta')
    # ### end Alembic commands ###
