"""agrega api whatsapp: conexion, contacto, conversacion, mensaje

Revision ID: fa6570a16866
Revises: e58444c07306
Create Date: 2026-08-16 21:31:05.207319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6570a16866'
down_revision = 'e58444c07306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_conexiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=60), nullable=False),
    sa.Column('whatsapp_business_account_id', sa.String(length=60), nullable=False),
    sa.Column('access_token_cifrado', sa.Text(), nullable=False),
    sa.Column('verify_token_cifrado', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ultima_sincronizacion_en', sa.DateTime(), nullable=True),
    sa.Column('configurado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configurado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_conexiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_conexiones_empresa_id'), ['empresa_id'], unique=True)

    op.create_table('whatsapp_contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['whatsapp_conexiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'telefono', name='uq_whatsapp_contacto_empresa_telefono')
    )
    with op.batch_alter_table('whatsapp_contactos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_contactos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('whatsapp_conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('leida_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['whatsapp_contactos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_conversaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_conversaciones_contacto_id'), ['contacto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversaciones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('whatsapp_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('id_externo', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['whatsapp_conversaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_externo')
    )
    with op.batch_alter_table('whatsapp_mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_mensajes_conversacion_id'), ['conversacion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_mensajes_conversacion_id'))

    op.drop_table('whatsapp_mensajes')
    with op.batch_alter_table('whatsapp_conversaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversaciones_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversaciones_contacto_id'))

    op.drop_table('whatsapp_conversaciones')
    with op.batch_alter_table('whatsapp_contactos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_contactos_empresa_id'))

    op.drop_table('whatsapp_contactos')
    with op.batch_alter_table('whatsapp_conexiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_conexiones_empresa_id'))

    op.drop_table('whatsapp_conexiones')
    # ### end Alembic commands ###
