"""agrega actualizado_en a usuarios y empresas

Revision ID: fa7baefa9095
Revises: dbb528fc72ec
Create Date: 2026-08-11 22:38:00.582128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7baefa9095'
down_revision = 'dbb528fc72ec'
branch_labels = None
depends_on = None

roles_tabla = sa.table(
    "roles",
    sa.column("nombre", sa.String),
    sa.column("descripcion", sa.String),
)

ROLES_BASE = [
    {"nombre": "Administrador", "descripcion": "Acceso total a la empresa."},
    {"nombre": "Editor", "descripcion": "Puede crear y editar contenido de la empresa."},
    {"nombre": "Cliente", "descripcion": "Acceso de solo lectura a la empresa."},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(), nullable=False))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###

    # Roles base del sistema multiempresa (no son datos ficticios de
    # prueba: son catalogo real que la aplicacion necesita para
    # funcionar, por eso se siembra via migracion y no a mano).
    op.bulk_insert(roles_tabla, ROLES_BASE)


def downgrade():
    op.execute(
        roles_tabla.delete().where(
            roles_tabla.c.nombre.in_([r["nombre"] for r in ROLES_BASE])
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('actualizado_en')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('actualizado_en')

    # ### end Alembic commands ###
