"""Agrega proyectos estrategicos, fases y secuencia (Paso 9)

Revision ID: fdff157b5aa8
Revises: 762d36bff20f
Create Date: 2026-08-14 01:28:08.000093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdff157b5aa8'
down_revision = '762d36bff20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_estrategicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_publicitaria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('objetivo', sa.String(length=120), nullable=False),
    sa.Column('kpi_principal', sa.String(length=60), nullable=False),
    sa.Column('kpi_secundarios', sa.JSON(), nullable=False),
    sa.Column('presupuesto_total', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('resultado_objetivo', sa.String(length=200), nullable=True),
    sa.Column('restricciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_publicitaria_id'], ['entidades_publicitarias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos_estrategicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_estrategicos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('fases_estrategicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('objetivo', sa.String(length=120), nullable=True),
    sa.Column('presupuesto', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('kpi_esperado', sa.String(length=60), nullable=True),
    sa.Column('audiencia_tipo', sa.String(length=40), nullable=True),
    sa.Column('audiencia_descripcion', sa.String(length=200), nullable=True),
    sa.Column('audiencia_entidad_id', sa.Integer(), nullable=True),
    sa.Column('resultado_esperado', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audiencia_entidad_id'], ['entidades_publicitarias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_estrategicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fases_estrategicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fases_estrategicas_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('pasos_secuencia_estrategica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=200), nullable=False),
    sa.Column('audiencia_descripcion', sa.String(length=200), nullable=True),
    sa.Column('objetivo', sa.String(length=120), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('kpi', sa.String(length=60), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_estrategicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pasos_secuencia_estrategica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pasos_secuencia_estrategica_proyecto_id'), ['proyecto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasos_secuencia_estrategica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pasos_secuencia_estrategica_proyecto_id'))

    op.drop_table('pasos_secuencia_estrategica')
    with op.batch_alter_table('fases_estrategicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fases_estrategicas_proyecto_id'))

    op.drop_table('fases_estrategicas')
    with op.batch_alter_table('proyectos_estrategicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_estrategicos_empresa_id'))

    op.drop_table('proyectos_estrategicos')
    # ### end Alembic commands ###
